services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wcs_studio_dev
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data # 3. Persists your data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data: