name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          docker compose \
            -p wcs_studio \
            --env-file /home/karolhaf/wcs_studio/.env \
            -f docker-compose.prod.yml up -d --build

      - name: Cleanup
        run: docker image prune -f

      - name: Verify deployment
        run: |
          sleep 10
          docker compose -p wcs_studio ps