name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          docker compose up -f docker-compose.prod.yml -d --build

      - name: Cleanup
        run: docker image prune -f

      - name: Verify deployment
        run: |
          sleep 10
          docker compose ps
